const app=document.querySelector('#app'),modal=document.querySelector('#popup'),key='gopuzzler58-cancel-v1';
let s={stage:0,plan:'GoPuzzler+',entries:Array(8).fill(''),reason:'',verified:false,seen:[]};try{Object.assign(s,JSON.parse(localStorage.getItem(key)||'{}'));}catch{}
const save=()=>{try{localStorage.setItem(key,JSON.stringify(s));}catch{}};
const b=(text,action,quiet=false)=>`<button data-action="${action}" class="${quiet?'quiet':''}">${text}</button>`;
function pop(title,text,buttons){document.querySelector('#popup-content').innerHTML=`<h2 id="popup-title">${title}</h2><p>${text}</p>${buttons}`;if(!modal.open)modal.showModal();}
function ad(){pop('Thank you for your interest.','Your interest has been shared with our partners.',b('Close','close'));}
function distract(stage){if(s.seen.includes(stage))return;s.seen.push(stage);save();if(stage===1)pop('Existential Cloud','Back up this moment before you regret it.',b('Explore plans','ad')+b('No thanks, I’ll remember this.','close',true));if(stage===4)pop('Someone nearby just upgraded to Platinum.','Their circumstances may differ from yours.',b('Good for them','close'));if(stage===5)pop('Having trouble accessing your memories?','Existential Cloud can help.',b('Explore plans','ad')+b('No thanks, I kept notes.','close',true));}
function go(n){if(modal.open)modal.close();s.stage=n;save();render();window.scrollTo(0,0);if([1,4,5].includes(n))distract(n);}
function render(){let c='',title='Your free trial awaits';
if(s.stage===0)c=`<img class="photo" src="screen58-locked.jpg" alt="Level 58 — locked preview"><section class="card"><div class="eyebrow">Free puzzle limit reached — Subscribe to continue</div><h1>Continue with GoPuzzler+</h1><p>Unlock the next page</p><div class="plans"><section class="plan"><h2>GoPuzzler+</h2><div class="price">$10.99 <small>per month</small></div><p>One new page at a time.</p>${b('Start free trial','plus')}</section><section class="plan platinum"><h2>GoPuzzler Platinum</h2><div class="price">$24.99 <small>per month</small></div><p>All future passwords pre-saved in your browser.</p>${b('Start free trial','platinum')}</section></div><p class="fine">No payment method required.</p><p class="fine">Prices shown reflect monthly billing. Cancellation requires a brief exit interview. The illusion of ownership is included at no additional cost.</p></section><p class="eyebrow">Sponsored relevance</p><section class="ads">${[['Existential Cloud','Back up your memories.','Because remembering things yourself is a lot.','Start with 2GB free →'],['Air Premium','Out of free breaths?','Upgrade your atmosphere. Family plans include one guest wheeze.','Check availability →'],['Closure.ai','Closure is a recurring service.','Let our model explain why they stopped texting you.','Begin processing →']].map(a=>`<article class="ad"><div class="eyebrow">${a[0]}</div><h2>${a[1]}</h2><p>${a[2]}</p>${b(a[3],'ad')}</article>`).join('')}</section>`;
if(s.stage===1){title='Welcome aboard';c=`<h1>Your free trial is active.</h1><p>Unfortunately, “Continue” isn’t included in the trial.</p><p>Current plan: <strong>${s.plan==='GoPuzzler Platinum'?'GoPuzzler Platinum':'GoPuzzler+'}</strong></p>${b('Upgrade membership','upgrade')}${b('Manage subscription','manage',true)}`;}
if(s.stage===2){title='Your membership';c=`<h1>Your membership</h1><p>Status: Active trial<br>Payment method: Not required</p><p>To return to the free version, cancel your trial.</p>${b('Cancel trial','cancel')}`;}
if(s.stage===3){title='Before you go';c=`<h1>Are you sure you want less?</h1><p>We noticed you’re considering cancellation. Have you considered reconsidering?</p><p>Keep your membership and receive <strong>50% off your next imaginary invoice</strong>.</p>${b('Keep my subscription','keep')}${b('Continue cancellation','survey',true)}`;}
if(s.stage===4){title='Your feedback matters*';c=`<h1>Help us understand your decision.</h1><p>Please select the reason that best fits our reporting requirements.</p><form id="survey" class="survey">${['I have reached a financially responsible conclusion.','I thought this was a puzzle.','I prefer owning my ability to continue.','Other.'].map((t,i)=>`<label><input type="radio" name="reason" value="${i}" ${s.reason===String(i)?'checked':''}> ${t}</label>`).join('')}<p id="other" ${s.reason==='3'?'':'hidden'}>Unfortunately, we are not accepting other reasons at this time.</p><p class="error" role="status"></p><button>Continue cancellation</button></form><p class="fine">*Your feedback matters statistically.</p>`;}
if(s.stage===5){title='For your security';c=`<h1>Verify account ownership</h1><p>Starting a trial requires one click. Canceling one requires us to be certain it’s you.</p><p>Enter the requested characters from your previous GoPuzzler passwords.<br><strong>Passwords only. Usernames are not accepted. Count characters starting from 1.</strong></p><p>Read your entries from top to bottom to form your cancellation key.</p><form id="verify" class="fields">${[[7,3],[9,2],[11,5],[20,2],[23,3],[32,3],[34,1],[35,4]].map(([l,n],i)=>`<label>Level ${l} — Password character ${n}<input data-entry="${i}" maxlength="1" autocomplete="off" spellcheck="false" aria-label="Level ${l} password character ${n}"></label>`).join('')}<p class="error" role="status"></p><button>Verify ownership</button></form>`;}
if(s.stage===6){title='One last thing';c=`<h1>Account ownership verified.</h1><p>You are about to lose:</p><ul><li>Recurring interruptions</li><li>Personalized upgrade opportunities</li><li>Your valued subscriber status</li></ul><p>Your ability to solve puzzles independently will remain unaffected.</p>${b('Keep subscription','manage')} ${b('Confirm cancellation','confirm')}`;}
if(s.stage===7){title='You’re free';c=`<h1>Subscription canceled.</h1><p>You’re free to continue.</p><a class="button" id="next">Continue</a>`;}
document.title=title;const step=({1:1,2:1,3:2,4:3,5:4,6:5})[s.stage];app.innerHTML=s.stage===0?c:`<section class="card">${step?`<div class="eyebrow">${step} / 5</div>`:''}${c}</section>`;document.querySelectorAll('[data-entry]').forEach(el=>el.value=s.entries[Number(el.dataset.entry)]||'');if(s.stage===7)document.querySelector('#next').href=s.entries.join('').replace(/[^a-z]/gi,'').toLowerCase()+'.htm';}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;switch(el.dataset.action){case'close':modal.close();break;case'ad':ad();break;case'plus':case'platinum':s.plan=el.dataset.action==='plus'?'GoPuzzler+':'GoPuzzler Platinum';go(1);break;case'upgrade':pop('You deserve more.','Additional membership options are currently being invented.',b('Return to membership','close'));break;case'manage':go(2);break;case'cancel':go(3);break;case'keep':pop('Excellent decision.','Your cancellation has been canceled.',b('Return to membership','manage'));break;case'survey':go(4);break;case'confirm':if(s.verified)go(7);break;}});
document.addEventListener('change',e=>{if(e.target.name==='reason'){s.reason=e.target.value;save();document.querySelector('#other').hidden=s.reason!=='3';}});
document.addEventListener('input',e=>{if(e.target.dataset.entry!==undefined){const i=Number(e.target.dataset.entry);s.entries[i]=e.target.value.replace(/[^a-z]/gi,'').toLowerCase();e.target.value=s.entries[i];save();}});
document.addEventListener('submit',e=>{e.preventDefault();const error=e.target.querySelector('.error');if(e.target.id==='survey'){if(s.reason===''){error.textContent='Please select a reason so we can disregard it accurately.';return;}go(s.verified?6:5);}if(e.target.id==='verify'){if(s.entries.some(x=>!x)){error.textContent='Please complete all eight verification fields.';return;}let h=2166136261;for(const c of s.entries.join('').toLowerCase())h=Math.imul(h^c.charCodeAt(0),16777619)>>>0;if(h!==EXPECTED){error.textContent='We couldn’t verify account ownership. Check your previous passwords and the requested character positions.';return;}s.verified=true;go(6);}});
const EXPECTED=95340396;
render();
